version: '3.5'

services:
  redis:
    image: "redis:alpine"
  simple_api:
    build: .
    image: simple_api:main
    working_dir: /app
    command: /bin/bash scripts/start_api.sh
    volumes:
      - .:/app
      - ./static:/app/static
      - ./media:/app/media
    expose:
      - 8000
    depends_on:
      - redis
      - database
  celery:
    image: simple_api:main
    working_dir: /app
    command: /bin/bash scripts/celery.sh
    volumes:
      - .:/app
    depends_on:
      - redis
      - database
  celery-beat:
    image: simple_api:main
    working_dir: /app
    command: /bin/bash scripts/celery_beat.sh
    volumes:
      - .:/app
    depends_on:
      - redis
      - database

  nginx:
    build: ./config/nginx/
    ports:
      - 8000:80
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - simple_api

  database:
    image: postgres:10
    env_file:
      - config/db/database_env
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
 pg_data:
