aliases:
  - &heroku-login
      name: Heroku login
      command: |
        cat >~/.netrc <<EOF
        machine api.heroku.com
          login $HEROKU_EMAIL
          password $HEROKU_API_KEY
        machine git.heroku.com
          login $HEROKU_EMAIL
          password $HEROKU_API_KEY
        EOF
        chmod 600 ~/.netrc

  - &heroku-deploy
      name: Deploy to Heroku
      command: |
        git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git master

  - &heroku-apply-migrations
      name: Run migrations
      command: |
        heroku run --app $HEROKU_APP python src/manage.py migrate

  - &delploy-master-branch
      requires:
        - build
      filters:
        branches:
          only: master


version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build image
          command: docker-compose build
      - run:
          name: Bring up docker container for server
          command: docker-compose up -d
      - run:
          name: Run server tests
          command: |
            docker-compose run simple_api python src/manage.py test src

  deploy-simple-api:
    machine: true
    environment:
      HEROKU_APP: "dry-shelf-98071"
    steps:
      - checkout
#      - run: *heroku-login
      - run: *heroku-deploy
      - run: *heroku-apply-migrations


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-simple-api:
          *delploy-master-branch

