# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180820_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='site',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
