# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180822_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='site',
            field=models.CharField(blank=True, default='', max_length=120),
            preserve_default=False,
        ),
    ]
